name: Hello World CI

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello World!"
      - name: Show OS
        run: uname -a

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la
